name: docker activities

on: 
    workflow_dispatch:
        inputs:
            my_input:
                description: My input description
                required: false
                type: string

jobs:
    docker:
        runs-on: ubuntu-latest

        steps:
            - name: Docker Login
              run: docker login --username=${{ vars.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PWD }}
