name: docker activities

on: push

jobs:
    docker:
        runs-on: ubuntu-latest

        steps:
            - name: Docker Login
              run: docker login --username=${{ vars.docker_username }} --password=${{ secrets.docker_pwd }}
