name: my first gihub action | shell script

on: push

jobs:
    job1:
        runs-on: ubuntu-latest
        steps:
            - name: checkout repo
              uses: actions/checkout@v4
            
            - name: list files
              run:   ls -ltra

            - name: run shell script
              run: | 
                   chmod +x script.sh
                   chmod +x cowsay.sh
                   ./script.sh
                   ./cowsay.sh

            - name: upload to artifact
              uses: actions/upload-artifact@v4
              with:
                name: dragon-file
                path: dragon.txt  
